Troubleshooting kernel auto build processes. Changed the way the .config file is copied to the working directory. Must have not been copying correctly and not applying the new .config file.

diff --git a/config_generator b/config_generator
--- a/config_generator
+++ b/config_generator
@@ -116,14 +116,14 @@ function prepare_kernel () {
 	fi
 	"$ECHO" "Done."
 
-	# Select kernel for Rapberry Pi 4
-	"$ECHO" "Setting Kernel to Rasberry Pi 4"
-	if ! KERNEL=kernel7l ; then
-		result="$?"
-		failed_process="setting of up the Raspberry Pi 4 kernel"
-		handle_fails "$failed_process"
-	fi
-	"$ECHO" "Done."
+#	# Select kernel for Rapberry Pi 4
+#	"$ECHO" "Setting Kernel to Rasberry Pi 4"
+#	if ! KERNEL=kernel7l ; then
+#		result="$?"
+#		failed_process="setting of up the Raspberry Pi 4 kernel"
+#		handle_fails "$failed_process"
+#	fi
+#	"$ECHO" "Done."
 
 	# Set processor type for Raspberry Pi 4
 	"$ECHO" "Making bcm2711_defconfig..."
